Repository egc-veleta-g2/decide, pull requests merged in 2021-12, with the labels that each got.

#9 Implementar la configuración para la integración continua
  .github/workflows/django.yml
  decide/decide/settings.py
  requirements.txt
Labels: high priority, conf

#10 Implementar configuración para la integración continua
  .github/workflows/django.yml
  decide/decide/settings.py
  requirements.txt
Labels: high priority, conf

#13 Corregir despliegue en heroku
  Procfile
Labels: high priority, fix, conf

#14 Corregir despliegue en heroku
  Procfile
Labels: high priority, fix, conf

#15 Añadir bloque APIS
  decide/decide/settings.py
Labels: high priority, fix, conf

#16 Añadir bloque APIS
  decide/decide/settings.py
Labels: high priority, fix, conf

#17 Corregir base url
  decide/decide/settings.py
Labels: high priority, fix, conf

#18 Corregir base url
  decide/decide/settings.py
Labels: high priority, fix, conf

#24 Implementación de funcionalidad votación SI/NO
  decide/voting/forms.py
  decide/voting/templates/dichotomyform.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: feature, high priority

#25 Corrección en test por fallo de static files
  decide/voting/tests.py
Labels: high priority, fix

#30 Implementar la interfaz de votación si/no
  decide/admin/templates/admin/index.html
  decide/decide/settings.py
  decide/voting/forms.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/templates/typeform.html
  decide/voting/urls.py
  decide/voting/views.py
Labels: feature, medium priority

#31 Integración con docker
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: high priority, conf

#34 Implementar una vista de inicio para cabina
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/static/booth/inicio_style.css
  decide/booth/templates/booth/inicio.html
  decide/booth/urls.py
  decide/booth/views.py
Labels: feature, medium priority

#35 Implementar url personalizada en votación
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: feature, medium priority

#37 Corregir fallo de url de cabina
  decide/booth/urls.py
Labels: bug, high priority, fix

#38 Integración de las funcionalidades
  decide/admin/templates/admin/index.html
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/static/booth/inicio_style.css
  decide/booth/templates/booth/inicio.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/decide/settings.py
  decide/voting/forms.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/models.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/templates/dichotomyform.html
  decide/voting/templates/typeform.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: feature, high priority

#46 Creación de más test referente a la funcionalidad votación SI/NO para un aumento del coverage
  decide/voting/selenium/test_check.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/tests.py
Labels: feature, medium priority

#47 Creada funcionalidad de encuesta rápida junto con test
  decide/base/migrations/0001_initial.py
  decide/base/migrations/0002_auto_20180921_1056.py
  decide/base/migrations/0003_auto_20180921_1119.py
  decide/mixnet/migrations/0001_initial.py
  decide/mixnet/migrations/0002_auto_20180216_1617.py
  decide/mixnet/migrations/0003_mixnet_auth_position.py
  decide/mixnet/migrations/0004_auto_20180605_0842.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_vote_voted.py
  decide/store/migrations/0003_auto_20180921_1522.py
  decide/store/views.py
  decide/voting/migrations/0001_initial.py
  decide/voting/migrations/0002_auto_20180302_1100.py
  decide/voting/migrations/0002_auto_20211228_1829.py
  decide/voting/migrations/0003_auto_20180605_0842.py
  decide/voting/migrations/0003_auto_20211228_1830.py
  decide/voting/migrations/0004_auto_20211228_1836.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/migrations/0005_auto_20211228_1845.py
  decide/voting/migrations/0006_auto_20211228_1846.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: feature, medium priority

#50 Añadidos dos nuevos tests unitarios
  decide/voting/tests.py
Labels: feature, medium priority

#51 Añadida funcionalidad para resetear votación
  decide/voting/admin.py
  decide/voting/selenium/test_acciones_votacion.py
  decide/voting/selenium/test_mensajes_acciones.py
  decide/voting/tests.py
Labels: feature, low priority

#52 Arreglar error en inicio de cabina y nuevos tests unitarios
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/templates/booth/inicio.html
  decide/booth/views.py
  decide/voting/tests.py
Labels: feature, high priority, fix
