Repository egc-veleta-g2/decide, pull requests merged in 2022-01, with the labels that each got.

#64 Conf/63 integracion repo padre
  .github/ISSUE_TEMPLATE/incidencia.md
  .github/workflows/django.yml
  .gitignore
  decide/base/migrations/0001_initial.py
  decide/base/templates/base.html
  decide/base/templates/inicio.html
  decide/base/views.py
  decide/booth/static/booth/style.css
  decide/booth/static/js/grafica_visualizer.js
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/census/migrations/0001_initial.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/mixnet/migrations/0001_initial.py
  decide/store/migrations/0001_initial.py
  decide/visualizer/migrations/datos_prueba.json
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/migrations/0001_initial.py
  decide/voting/migrations/0002_auto_20211228_1829.py
  decide/voting/migrations/0003_auto_20211228_1830.py
  decide/voting/migrations/0004_auto_20211228_1836.py
  decide/voting/migrations/0005_auto_20211228_1845.py
  decide/voting/migrations/0006_auto_20211228_1846.py
  decide/voting/tests.py
  docker/docker-settings.py
  requirements.txt
Labels: high priority, conf

#65 conf : Crear plantilla automática para commits #62
  .gitmessage.txt
Labels: low priority, conf

#67 fix : Eliminar import no usado #62
  decide/voting/selenium/test_mensajes_acciones.py
Labels: fix, low priority

#66 Integración de las funcionalidades
  .github/ISSUE_TEMPLATE/incidencia.md
  .github/workflows/django.yml
  .gitmessage.txt
  decide/base/migrations/0001_initial.py
  decide/base/migrations/0002_auto_20180921_1056.py
  decide/base/migrations/0003_auto_20180921_1119.py
  decide/base/templates/base.html
  decide/base/templates/inicio.html
  decide/base/views.py
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/static/booth/style.css
  decide/booth/static/js/grafica_visualizer.js
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/inicio.html
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/migrations/0001_initial.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/mixnet/migrations/0001_initial.py
  decide/mixnet/migrations/0002_auto_20180216_1617.py
  decide/mixnet/migrations/0003_mixnet_auth_position.py
  decide/mixnet/migrations/0004_auto_20180605_0842.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_vote_voted.py
  decide/store/migrations/0003_auto_20180921_1522.py
  decide/store/views.py
  decide/visualizer/migrations/datos_prueba.json
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/migrations/0001_initial.py
  decide/voting/migrations/0002_auto_20180302_1100.py
  decide/voting/migrations/0003_auto_20180605_0842.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/models.py
  decide/voting/selenium/test_acciones_votacion.py
  decide/voting/selenium/test_check.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/selenium/test_mensajes_acciones.py
  decide/voting/tests.py
  docker/docker-settings.py
  requirements.txt
Labels: feature, high priority

#71 Feature/3 definir ordenacion por preferencia
  decide/authentication/tests.py
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/store/migrations/0002_auto_20220104_1042.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/selenium/test_create_order_question_Empty.py
  decide/voting/selenium/test_create_order_question_positive.py
  decide/voting/selenium/test_create_order_question_without_desc.py
  decide/voting/selenium/test_create_voting_order_question_positive.py
  decide/voting/serializers.py
  decide/voting/tests.py
Labels: feature, high priority

#77 Conf/5 integracion continua
  README.md
Labels: low priority, conf

#79 Feature/26 url votacion configurable
  decide/booth/tests.py
Labels: bug, low priority

#80 Develop
  README.md
  decide/authentication/tests.py
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/booth/views.py
  decide/store/migrations/0002_auto_20220104_1042.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/voting/forms.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/selenium/test_create_order_question_Empty.py
  decide/voting/selenium/test_create_order_question_positive.py
  decide/voting/selenium/test_create_order_question_without_desc.py
  decide/voting/selenium/test_create_voting_order_question_positive.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: feature, high priority

#83 fix : Solucionar migraciones #81
  decide/base/migrations/0001_initial.py
  decide/census/migrations/0001_initial.py
  decide/mixnet/migrations/0001_initial.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_auto_20220104_1042.py
  decide/voting/migrations/0001_initial.py
Labels: high priority, conf

#84 Corrección de migraciones
  decide/base/migrations/0001_initial.py
  decide/census/migrations/0001_initial.py
  decide/mixnet/migrations/0001_initial.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_auto_20220104_1042.py
  decide/voting/migrations/0001_initial.py
Labels: high priority, conf

#86 test : Crear test de preguntas #3
  decide/voting/tests.py
Labels: feature, low priority

#89 Conf/5 integracion continua
  .github/workflows/django.yml
Labels: low priority, conf

#90 Funcionalidades y test finales para el M3
  .github/workflows/django.yml
  decide/voting/tests.py
Labels: feature, high priority

#93 Conf/5 integracion continua
  .github/workflows/django.yml
Labels: low priority, conf

#94 Modificado orden de ejecución
  .github/workflows/django.yml
Labels: low priority, conf
